// Code generated by ent, DO NOT EDIT.

package chatlist

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the chatlist type in the database.
	Label = "chat_list"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldUID holds the string denoting the uid field in the database.
	FieldUID = "uid"
	// FieldChannel holds the string denoting the channel field in the database.
	FieldChannel = "channel"
	// FieldChatID holds the string denoting the chat_id field in the database.
	FieldChatID = "chat_id"
	// FieldMaxMsgID holds the string denoting the max_msg_id field in the database.
	FieldMaxMsgID = "max_msg_id"
	// FieldUts holds the string denoting the uts field in the database.
	FieldUts = "uts"
	// FieldType holds the string denoting the type field in the database.
	FieldType = "type"
	// Table holds the table name of the chatlist in the database.
	Table = "chat_list"
)

// Columns holds all SQL columns for chatlist fields.
var Columns = []string{
	FieldID,
	FieldUID,
	FieldChannel,
	FieldChatID,
	FieldMaxMsgID,
	FieldUts,
	FieldType,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the ChatList queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByUID orders the results by the uid field.
func ByUID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUID, opts...).ToFunc()
}

// ByChannel orders the results by the channel field.
func ByChannel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChannel, opts...).ToFunc()
}

// ByChatID orders the results by the chat_id field.
func ByChatID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChatID, opts...).ToFunc()
}

// ByMaxMsgID orders the results by the max_msg_id field.
func ByMaxMsgID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxMsgID, opts...).ToFunc()
}

// ByUts orders the results by the uts field.
func ByUts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUts, opts...).ToFunc()
}

// ByType orders the results by the type field.
func ByType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldType, opts...).ToFunc()
}
