// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/im/common/data/ent/chatlist"
	"github.com/im/common/data/ent/predicate"
)

// ChatListQuery is the builder for querying ChatList entities.
type ChatListQuery struct {
	config
	ctx        *QueryContext
	order      []chatlist.OrderOption
	inters     []Interceptor
	predicates []predicate.ChatList
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the ChatListQuery builder.
func (clq *ChatListQuery) Where(ps ...predicate.ChatList) *ChatListQuery {
	clq.predicates = append(clq.predicates, ps...)
	return clq
}

// Limit the number of records to be returned by this query.
func (clq *ChatListQuery) Limit(limit int) *ChatListQuery {
	clq.ctx.Limit = &limit
	return clq
}

// Offset to start from.
func (clq *ChatListQuery) Offset(offset int) *ChatListQuery {
	clq.ctx.Offset = &offset
	return clq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (clq *ChatListQuery) Unique(unique bool) *ChatListQuery {
	clq.ctx.Unique = &unique
	return clq
}

// Order specifies how the records should be ordered.
func (clq *ChatListQuery) Order(o ...chatlist.OrderOption) *ChatListQuery {
	clq.order = append(clq.order, o...)
	return clq
}

// First returns the first ChatList entity from the query.
// Returns a *NotFoundError when no ChatList was found.
func (clq *ChatListQuery) First(ctx context.Context) (*ChatList, error) {
	nodes, err := clq.Limit(1).All(setContextOp(ctx, clq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{chatlist.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (clq *ChatListQuery) FirstX(ctx context.Context) *ChatList {
	node, err := clq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first ChatList ID from the query.
// Returns a *NotFoundError when no ChatList ID was found.
func (clq *ChatListQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = clq.Limit(1).IDs(setContextOp(ctx, clq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{chatlist.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (clq *ChatListQuery) FirstIDX(ctx context.Context) int64 {
	id, err := clq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single ChatList entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one ChatList entity is found.
// Returns a *NotFoundError when no ChatList entities are found.
func (clq *ChatListQuery) Only(ctx context.Context) (*ChatList, error) {
	nodes, err := clq.Limit(2).All(setContextOp(ctx, clq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{chatlist.Label}
	default:
		return nil, &NotSingularError{chatlist.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (clq *ChatListQuery) OnlyX(ctx context.Context) *ChatList {
	node, err := clq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only ChatList ID in the query.
// Returns a *NotSingularError when more than one ChatList ID is found.
// Returns a *NotFoundError when no entities are found.
func (clq *ChatListQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = clq.Limit(2).IDs(setContextOp(ctx, clq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{chatlist.Label}
	default:
		err = &NotSingularError{chatlist.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (clq *ChatListQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := clq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of ChatLists.
func (clq *ChatListQuery) All(ctx context.Context) ([]*ChatList, error) {
	ctx = setContextOp(ctx, clq.ctx, "All")
	if err := clq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*ChatList, *ChatListQuery]()
	return withInterceptors[[]*ChatList](ctx, clq, qr, clq.inters)
}

// AllX is like All, but panics if an error occurs.
func (clq *ChatListQuery) AllX(ctx context.Context) []*ChatList {
	nodes, err := clq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of ChatList IDs.
func (clq *ChatListQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if clq.ctx.Unique == nil && clq.path != nil {
		clq.Unique(true)
	}
	ctx = setContextOp(ctx, clq.ctx, "IDs")
	if err = clq.Select(chatlist.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (clq *ChatListQuery) IDsX(ctx context.Context) []int64 {
	ids, err := clq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (clq *ChatListQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, clq.ctx, "Count")
	if err := clq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, clq, querierCount[*ChatListQuery](), clq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (clq *ChatListQuery) CountX(ctx context.Context) int {
	count, err := clq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (clq *ChatListQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, clq.ctx, "Exist")
	switch _, err := clq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (clq *ChatListQuery) ExistX(ctx context.Context) bool {
	exist, err := clq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the ChatListQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (clq *ChatListQuery) Clone() *ChatListQuery {
	if clq == nil {
		return nil
	}
	return &ChatListQuery{
		config:     clq.config,
		ctx:        clq.ctx.Clone(),
		order:      append([]chatlist.OrderOption{}, clq.order...),
		inters:     append([]Interceptor{}, clq.inters...),
		predicates: append([]predicate.ChatList{}, clq.predicates...),
		// clone intermediate query.
		sql:  clq.sql.Clone(),
		path: clq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		UID int64 `json:"uid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.ChatList.Query().
//		GroupBy(chatlist.FieldUID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (clq *ChatListQuery) GroupBy(field string, fields ...string) *ChatListGroupBy {
	clq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &ChatListGroupBy{build: clq}
	grbuild.flds = &clq.ctx.Fields
	grbuild.label = chatlist.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		UID int64 `json:"uid,omitempty"`
//	}
//
//	client.ChatList.Query().
//		Select(chatlist.FieldUID).
//		Scan(ctx, &v)
func (clq *ChatListQuery) Select(fields ...string) *ChatListSelect {
	clq.ctx.Fields = append(clq.ctx.Fields, fields...)
	sbuild := &ChatListSelect{ChatListQuery: clq}
	sbuild.label = chatlist.Label
	sbuild.flds, sbuild.scan = &clq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a ChatListSelect configured with the given aggregations.
func (clq *ChatListQuery) Aggregate(fns ...AggregateFunc) *ChatListSelect {
	return clq.Select().Aggregate(fns...)
}

func (clq *ChatListQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range clq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, clq); err != nil {
				return err
			}
		}
	}
	for _, f := range clq.ctx.Fields {
		if !chatlist.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if clq.path != nil {
		prev, err := clq.path(ctx)
		if err != nil {
			return err
		}
		clq.sql = prev
	}
	return nil
}

func (clq *ChatListQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*ChatList, error) {
	var (
		nodes = []*ChatList{}
		_spec = clq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*ChatList).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &ChatList{config: clq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, clq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (clq *ChatListQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := clq.querySpec()
	_spec.Node.Columns = clq.ctx.Fields
	if len(clq.ctx.Fields) > 0 {
		_spec.Unique = clq.ctx.Unique != nil && *clq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, clq.driver, _spec)
}

func (clq *ChatListQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(chatlist.Table, chatlist.Columns, sqlgraph.NewFieldSpec(chatlist.FieldID, field.TypeInt64))
	_spec.From = clq.sql
	if unique := clq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if clq.path != nil {
		_spec.Unique = true
	}
	if fields := clq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, chatlist.FieldID)
		for i := range fields {
			if fields[i] != chatlist.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := clq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := clq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := clq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := clq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (clq *ChatListQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(clq.driver.Dialect())
	t1 := builder.Table(chatlist.Table)
	columns := clq.ctx.Fields
	if len(columns) == 0 {
		columns = chatlist.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if clq.sql != nil {
		selector = clq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if clq.ctx.Unique != nil && *clq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range clq.predicates {
		p(selector)
	}
	for _, p := range clq.order {
		p(selector)
	}
	if offset := clq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := clq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// ChatListGroupBy is the group-by builder for ChatList entities.
type ChatListGroupBy struct {
	selector
	build *ChatListQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (clgb *ChatListGroupBy) Aggregate(fns ...AggregateFunc) *ChatListGroupBy {
	clgb.fns = append(clgb.fns, fns...)
	return clgb
}

// Scan applies the selector query and scans the result into the given value.
func (clgb *ChatListGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, clgb.build.ctx, "GroupBy")
	if err := clgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChatListQuery, *ChatListGroupBy](ctx, clgb.build, clgb, clgb.build.inters, v)
}

func (clgb *ChatListGroupBy) sqlScan(ctx context.Context, root *ChatListQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(clgb.fns))
	for _, fn := range clgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*clgb.flds)+len(clgb.fns))
		for _, f := range *clgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*clgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := clgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// ChatListSelect is the builder for selecting fields of ChatList entities.
type ChatListSelect struct {
	*ChatListQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (cls *ChatListSelect) Aggregate(fns ...AggregateFunc) *ChatListSelect {
	cls.fns = append(cls.fns, fns...)
	return cls
}

// Scan applies the selector query and scans the result into the given value.
func (cls *ChatListSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, cls.ctx, "Select")
	if err := cls.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*ChatListQuery, *ChatListSelect](ctx, cls.ChatListQuery, cls, cls.inters, v)
}

func (cls *ChatListSelect) sqlScan(ctx context.Context, root *ChatListQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(cls.fns))
	for _, fn := range cls.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*cls.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := cls.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
