// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/im/common/data/ent/friend"
)

// Friend is the model entity for the Friend schema.
type Friend struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UID holds the value of the "uid" field.
	UID int64 `json:"uid,omitempty"`
	// PeerUID holds the value of the "peer_uid" field.
	PeerUID int64 `json:"peer_uid,omitempty"`
	// State holds the value of the "state" field.
	State int `json:"state,omitempty"`
	// Cts holds the value of the "cts" field.
	Cts int64 `json:"cts,omitempty"`
	// Uts holds the value of the "uts" field.
	Uts          int64 `json:"uts,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Friend) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case friend.FieldID, friend.FieldUID, friend.FieldPeerUID, friend.FieldState, friend.FieldCts, friend.FieldUts:
			values[i] = new(sql.NullInt64)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Friend fields.
func (f *Friend) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case friend.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			f.ID = int64(value.Int64)
		case friend.FieldUID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field uid", values[i])
			} else if value.Valid {
				f.UID = value.Int64
			}
		case friend.FieldPeerUID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field peer_uid", values[i])
			} else if value.Valid {
				f.PeerUID = value.Int64
			}
		case friend.FieldState:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field state", values[i])
			} else if value.Valid {
				f.State = int(value.Int64)
			}
		case friend.FieldCts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field cts", values[i])
			} else if value.Valid {
				f.Cts = value.Int64
			}
		case friend.FieldUts:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field uts", values[i])
			} else if value.Valid {
				f.Uts = value.Int64
			}
		default:
			f.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Friend.
// This includes values selected through modifiers, order, etc.
func (f *Friend) Value(name string) (ent.Value, error) {
	return f.selectValues.Get(name)
}

// Update returns a builder for updating this Friend.
// Note that you need to call Friend.Unwrap() before calling this method if this Friend
// was returned from a transaction, and the transaction was committed or rolled back.
func (f *Friend) Update() *FriendUpdateOne {
	return NewFriendClient(f.config).UpdateOne(f)
}

// Unwrap unwraps the Friend entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (f *Friend) Unwrap() *Friend {
	_tx, ok := f.config.driver.(*txDriver)
	if !ok {
		panic("ent: Friend is not a transactional entity")
	}
	f.config.driver = _tx.drv
	return f
}

// String implements the fmt.Stringer.
func (f *Friend) String() string {
	var builder strings.Builder
	builder.WriteString("Friend(")
	builder.WriteString(fmt.Sprintf("id=%v, ", f.ID))
	builder.WriteString("uid=")
	builder.WriteString(fmt.Sprintf("%v", f.UID))
	builder.WriteString(", ")
	builder.WriteString("peer_uid=")
	builder.WriteString(fmt.Sprintf("%v", f.PeerUID))
	builder.WriteString(", ")
	builder.WriteString("state=")
	builder.WriteString(fmt.Sprintf("%v", f.State))
	builder.WriteString(", ")
	builder.WriteString("cts=")
	builder.WriteString(fmt.Sprintf("%v", f.Cts))
	builder.WriteString(", ")
	builder.WriteString("uts=")
	builder.WriteString(fmt.Sprintf("%v", f.Uts))
	builder.WriteByte(')')
	return builder.String()
}

// Friends is a parsable slice of Friend.
type Friends []*Friend
