// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/im/common/data/ent/immsg"
	"github.com/im/common/data/ent/predicate"
)

// IMMsgQuery is the builder for querying IMMsg entities.
type IMMsgQuery struct {
	config
	ctx        *QueryContext
	order      []immsg.OrderOption
	inters     []Interceptor
	predicates []predicate.IMMsg
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the IMMsgQuery builder.
func (imq *IMMsgQuery) Where(ps ...predicate.IMMsg) *IMMsgQuery {
	imq.predicates = append(imq.predicates, ps...)
	return imq
}

// Limit the number of records to be returned by this query.
func (imq *IMMsgQuery) Limit(limit int) *IMMsgQuery {
	imq.ctx.Limit = &limit
	return imq
}

// Offset to start from.
func (imq *IMMsgQuery) Offset(offset int) *IMMsgQuery {
	imq.ctx.Offset = &offset
	return imq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (imq *IMMsgQuery) Unique(unique bool) *IMMsgQuery {
	imq.ctx.Unique = &unique
	return imq
}

// Order specifies how the records should be ordered.
func (imq *IMMsgQuery) Order(o ...immsg.OrderOption) *IMMsgQuery {
	imq.order = append(imq.order, o...)
	return imq
}

// First returns the first IMMsg entity from the query.
// Returns a *NotFoundError when no IMMsg was found.
func (imq *IMMsgQuery) First(ctx context.Context) (*IMMsg, error) {
	nodes, err := imq.Limit(1).All(setContextOp(ctx, imq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{immsg.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (imq *IMMsgQuery) FirstX(ctx context.Context) *IMMsg {
	node, err := imq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first IMMsg ID from the query.
// Returns a *NotFoundError when no IMMsg ID was found.
func (imq *IMMsgQuery) FirstID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = imq.Limit(1).IDs(setContextOp(ctx, imq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{immsg.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (imq *IMMsgQuery) FirstIDX(ctx context.Context) int64 {
	id, err := imq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single IMMsg entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one IMMsg entity is found.
// Returns a *NotFoundError when no IMMsg entities are found.
func (imq *IMMsgQuery) Only(ctx context.Context) (*IMMsg, error) {
	nodes, err := imq.Limit(2).All(setContextOp(ctx, imq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{immsg.Label}
	default:
		return nil, &NotSingularError{immsg.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (imq *IMMsgQuery) OnlyX(ctx context.Context) *IMMsg {
	node, err := imq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only IMMsg ID in the query.
// Returns a *NotSingularError when more than one IMMsg ID is found.
// Returns a *NotFoundError when no entities are found.
func (imq *IMMsgQuery) OnlyID(ctx context.Context) (id int64, err error) {
	var ids []int64
	if ids, err = imq.Limit(2).IDs(setContextOp(ctx, imq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{immsg.Label}
	default:
		err = &NotSingularError{immsg.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (imq *IMMsgQuery) OnlyIDX(ctx context.Context) int64 {
	id, err := imq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of IMMsgs.
func (imq *IMMsgQuery) All(ctx context.Context) ([]*IMMsg, error) {
	ctx = setContextOp(ctx, imq.ctx, "All")
	if err := imq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*IMMsg, *IMMsgQuery]()
	return withInterceptors[[]*IMMsg](ctx, imq, qr, imq.inters)
}

// AllX is like All, but panics if an error occurs.
func (imq *IMMsgQuery) AllX(ctx context.Context) []*IMMsg {
	nodes, err := imq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of IMMsg IDs.
func (imq *IMMsgQuery) IDs(ctx context.Context) (ids []int64, err error) {
	if imq.ctx.Unique == nil && imq.path != nil {
		imq.Unique(true)
	}
	ctx = setContextOp(ctx, imq.ctx, "IDs")
	if err = imq.Select(immsg.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (imq *IMMsgQuery) IDsX(ctx context.Context) []int64 {
	ids, err := imq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (imq *IMMsgQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, imq.ctx, "Count")
	if err := imq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, imq, querierCount[*IMMsgQuery](), imq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (imq *IMMsgQuery) CountX(ctx context.Context) int {
	count, err := imq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (imq *IMMsgQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, imq.ctx, "Exist")
	switch _, err := imq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (imq *IMMsgQuery) ExistX(ctx context.Context) bool {
	exist, err := imq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the IMMsgQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (imq *IMMsgQuery) Clone() *IMMsgQuery {
	if imq == nil {
		return nil
	}
	return &IMMsgQuery{
		config:     imq.config,
		ctx:        imq.ctx.Clone(),
		order:      append([]immsg.OrderOption{}, imq.order...),
		inters:     append([]Interceptor{}, imq.inters...),
		predicates: append([]predicate.IMMsg{}, imq.predicates...),
		// clone intermediate query.
		sql:  imq.sql.Clone(),
		path: imq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Sid string `json:"sid,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.IMMsg.Query().
//		GroupBy(immsg.FieldSid).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (imq *IMMsgQuery) GroupBy(field string, fields ...string) *IMMsgGroupBy {
	imq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &IMMsgGroupBy{build: imq}
	grbuild.flds = &imq.ctx.Fields
	grbuild.label = immsg.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Sid string `json:"sid,omitempty"`
//	}
//
//	client.IMMsg.Query().
//		Select(immsg.FieldSid).
//		Scan(ctx, &v)
func (imq *IMMsgQuery) Select(fields ...string) *IMMsgSelect {
	imq.ctx.Fields = append(imq.ctx.Fields, fields...)
	sbuild := &IMMsgSelect{IMMsgQuery: imq}
	sbuild.label = immsg.Label
	sbuild.flds, sbuild.scan = &imq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a IMMsgSelect configured with the given aggregations.
func (imq *IMMsgQuery) Aggregate(fns ...AggregateFunc) *IMMsgSelect {
	return imq.Select().Aggregate(fns...)
}

func (imq *IMMsgQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range imq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, imq); err != nil {
				return err
			}
		}
	}
	for _, f := range imq.ctx.Fields {
		if !immsg.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if imq.path != nil {
		prev, err := imq.path(ctx)
		if err != nil {
			return err
		}
		imq.sql = prev
	}
	return nil
}

func (imq *IMMsgQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*IMMsg, error) {
	var (
		nodes = []*IMMsg{}
		_spec = imq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*IMMsg).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &IMMsg{config: imq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, imq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (imq *IMMsgQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := imq.querySpec()
	_spec.Node.Columns = imq.ctx.Fields
	if len(imq.ctx.Fields) > 0 {
		_spec.Unique = imq.ctx.Unique != nil && *imq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, imq.driver, _spec)
}

func (imq *IMMsgQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(immsg.Table, immsg.Columns, sqlgraph.NewFieldSpec(immsg.FieldID, field.TypeInt64))
	_spec.From = imq.sql
	if unique := imq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if imq.path != nil {
		_spec.Unique = true
	}
	if fields := imq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, immsg.FieldID)
		for i := range fields {
			if fields[i] != immsg.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := imq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := imq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := imq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := imq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (imq *IMMsgQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(imq.driver.Dialect())
	t1 := builder.Table(immsg.Table)
	columns := imq.ctx.Fields
	if len(columns) == 0 {
		columns = immsg.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if imq.sql != nil {
		selector = imq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if imq.ctx.Unique != nil && *imq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range imq.predicates {
		p(selector)
	}
	for _, p := range imq.order {
		p(selector)
	}
	if offset := imq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := imq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// IMMsgGroupBy is the group-by builder for IMMsg entities.
type IMMsgGroupBy struct {
	selector
	build *IMMsgQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (imgb *IMMsgGroupBy) Aggregate(fns ...AggregateFunc) *IMMsgGroupBy {
	imgb.fns = append(imgb.fns, fns...)
	return imgb
}

// Scan applies the selector query and scans the result into the given value.
func (imgb *IMMsgGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, imgb.build.ctx, "GroupBy")
	if err := imgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IMMsgQuery, *IMMsgGroupBy](ctx, imgb.build, imgb, imgb.build.inters, v)
}

func (imgb *IMMsgGroupBy) sqlScan(ctx context.Context, root *IMMsgQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(imgb.fns))
	for _, fn := range imgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*imgb.flds)+len(imgb.fns))
		for _, f := range *imgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*imgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := imgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// IMMsgSelect is the builder for selecting fields of IMMsg entities.
type IMMsgSelect struct {
	*IMMsgQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (ims *IMMsgSelect) Aggregate(fns ...AggregateFunc) *IMMsgSelect {
	ims.fns = append(ims.fns, fns...)
	return ims
}

// Scan applies the selector query and scans the result into the given value.
func (ims *IMMsgSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, ims.ctx, "Select")
	if err := ims.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*IMMsgQuery, *IMMsgSelect](ctx, ims.IMMsgQuery, ims, ims.inters, v)
}

func (ims *IMMsgSelect) sqlScan(ctx context.Context, root *IMMsgQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(ims.fns))
	for _, fn := range ims.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*ims.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ims.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
