// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/im/common/data/ent/msgbody"
	"github.com/im/common/data/ent/predicate"
)

// MsgBodyDelete is the builder for deleting a MsgBody entity.
type MsgBodyDelete struct {
	config
	hooks    []Hook
	mutation *MsgBodyMutation
}

// Where appends a list predicates to the MsgBodyDelete builder.
func (mbd *MsgBodyDelete) Where(ps ...predicate.MsgBody) *MsgBodyDelete {
	mbd.mutation.Where(ps...)
	return mbd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (mbd *MsgBodyDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, mbd.sqlExec, mbd.mutation, mbd.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (mbd *MsgBodyDelete) ExecX(ctx context.Context) int {
	n, err := mbd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (mbd *MsgBodyDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(msgbody.Table, sqlgraph.NewFieldSpec(msgbody.FieldID, field.TypeInt))
	if ps := mbd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, mbd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	mbd.mutation.done = true
	return affected, err
}

// MsgBodyDeleteOne is the builder for deleting a single MsgBody entity.
type MsgBodyDeleteOne struct {
	mbd *MsgBodyDelete
}

// Where appends a list predicates to the MsgBodyDelete builder.
func (mbdo *MsgBodyDeleteOne) Where(ps ...predicate.MsgBody) *MsgBodyDeleteOne {
	mbdo.mbd.mutation.Where(ps...)
	return mbdo
}

// Exec executes the deletion query.
func (mbdo *MsgBodyDeleteOne) Exec(ctx context.Context) error {
	n, err := mbdo.mbd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{msgbody.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (mbdo *MsgBodyDeleteOne) ExecX(ctx context.Context) {
	if err := mbdo.Exec(ctx); err != nil {
		panic(err)
	}
}
