// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/im/common/data/ent/msgbody"
	"github.com/im/common/data/ent/predicate"
)

// MsgBodyQuery is the builder for querying MsgBody entities.
type MsgBodyQuery struct {
	config
	ctx        *QueryContext
	order      []msgbody.OrderOption
	inters     []Interceptor
	predicates []predicate.MsgBody
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the MsgBodyQuery builder.
func (mbq *MsgBodyQuery) Where(ps ...predicate.MsgBody) *MsgBodyQuery {
	mbq.predicates = append(mbq.predicates, ps...)
	return mbq
}

// Limit the number of records to be returned by this query.
func (mbq *MsgBodyQuery) Limit(limit int) *MsgBodyQuery {
	mbq.ctx.Limit = &limit
	return mbq
}

// Offset to start from.
func (mbq *MsgBodyQuery) Offset(offset int) *MsgBodyQuery {
	mbq.ctx.Offset = &offset
	return mbq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (mbq *MsgBodyQuery) Unique(unique bool) *MsgBodyQuery {
	mbq.ctx.Unique = &unique
	return mbq
}

// Order specifies how the records should be ordered.
func (mbq *MsgBodyQuery) Order(o ...msgbody.OrderOption) *MsgBodyQuery {
	mbq.order = append(mbq.order, o...)
	return mbq
}

// First returns the first MsgBody entity from the query.
// Returns a *NotFoundError when no MsgBody was found.
func (mbq *MsgBodyQuery) First(ctx context.Context) (*MsgBody, error) {
	nodes, err := mbq.Limit(1).All(setContextOp(ctx, mbq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{msgbody.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (mbq *MsgBodyQuery) FirstX(ctx context.Context) *MsgBody {
	node, err := mbq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first MsgBody ID from the query.
// Returns a *NotFoundError when no MsgBody ID was found.
func (mbq *MsgBodyQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mbq.Limit(1).IDs(setContextOp(ctx, mbq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{msgbody.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (mbq *MsgBodyQuery) FirstIDX(ctx context.Context) int {
	id, err := mbq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single MsgBody entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one MsgBody entity is found.
// Returns a *NotFoundError when no MsgBody entities are found.
func (mbq *MsgBodyQuery) Only(ctx context.Context) (*MsgBody, error) {
	nodes, err := mbq.Limit(2).All(setContextOp(ctx, mbq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{msgbody.Label}
	default:
		return nil, &NotSingularError{msgbody.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (mbq *MsgBodyQuery) OnlyX(ctx context.Context) *MsgBody {
	node, err := mbq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only MsgBody ID in the query.
// Returns a *NotSingularError when more than one MsgBody ID is found.
// Returns a *NotFoundError when no entities are found.
func (mbq *MsgBodyQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = mbq.Limit(2).IDs(setContextOp(ctx, mbq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{msgbody.Label}
	default:
		err = &NotSingularError{msgbody.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (mbq *MsgBodyQuery) OnlyIDX(ctx context.Context) int {
	id, err := mbq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of MsgBodies.
func (mbq *MsgBodyQuery) All(ctx context.Context) ([]*MsgBody, error) {
	ctx = setContextOp(ctx, mbq.ctx, "All")
	if err := mbq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*MsgBody, *MsgBodyQuery]()
	return withInterceptors[[]*MsgBody](ctx, mbq, qr, mbq.inters)
}

// AllX is like All, but panics if an error occurs.
func (mbq *MsgBodyQuery) AllX(ctx context.Context) []*MsgBody {
	nodes, err := mbq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of MsgBody IDs.
func (mbq *MsgBodyQuery) IDs(ctx context.Context) (ids []int, err error) {
	if mbq.ctx.Unique == nil && mbq.path != nil {
		mbq.Unique(true)
	}
	ctx = setContextOp(ctx, mbq.ctx, "IDs")
	if err = mbq.Select(msgbody.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (mbq *MsgBodyQuery) IDsX(ctx context.Context) []int {
	ids, err := mbq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (mbq *MsgBodyQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, mbq.ctx, "Count")
	if err := mbq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, mbq, querierCount[*MsgBodyQuery](), mbq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (mbq *MsgBodyQuery) CountX(ctx context.Context) int {
	count, err := mbq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (mbq *MsgBodyQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, mbq.ctx, "Exist")
	switch _, err := mbq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (mbq *MsgBodyQuery) ExistX(ctx context.Context) bool {
	exist, err := mbq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the MsgBodyQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (mbq *MsgBodyQuery) Clone() *MsgBodyQuery {
	if mbq == nil {
		return nil
	}
	return &MsgBodyQuery{
		config:     mbq.config,
		ctx:        mbq.ctx.Clone(),
		order:      append([]msgbody.OrderOption{}, mbq.order...),
		inters:     append([]Interceptor{}, mbq.inters...),
		predicates: append([]predicate.MsgBody{}, mbq.predicates...),
		// clone intermediate query.
		sql:  mbq.sql.Clone(),
		path: mbq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		MsgID int64 `json:"msg_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.MsgBody.Query().
//		GroupBy(msgbody.FieldMsgID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (mbq *MsgBodyQuery) GroupBy(field string, fields ...string) *MsgBodyGroupBy {
	mbq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &MsgBodyGroupBy{build: mbq}
	grbuild.flds = &mbq.ctx.Fields
	grbuild.label = msgbody.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		MsgID int64 `json:"msg_id,omitempty"`
//	}
//
//	client.MsgBody.Query().
//		Select(msgbody.FieldMsgID).
//		Scan(ctx, &v)
func (mbq *MsgBodyQuery) Select(fields ...string) *MsgBodySelect {
	mbq.ctx.Fields = append(mbq.ctx.Fields, fields...)
	sbuild := &MsgBodySelect{MsgBodyQuery: mbq}
	sbuild.label = msgbody.Label
	sbuild.flds, sbuild.scan = &mbq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a MsgBodySelect configured with the given aggregations.
func (mbq *MsgBodyQuery) Aggregate(fns ...AggregateFunc) *MsgBodySelect {
	return mbq.Select().Aggregate(fns...)
}

func (mbq *MsgBodyQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range mbq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, mbq); err != nil {
				return err
			}
		}
	}
	for _, f := range mbq.ctx.Fields {
		if !msgbody.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if mbq.path != nil {
		prev, err := mbq.path(ctx)
		if err != nil {
			return err
		}
		mbq.sql = prev
	}
	return nil
}

func (mbq *MsgBodyQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*MsgBody, error) {
	var (
		nodes = []*MsgBody{}
		_spec = mbq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*MsgBody).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &MsgBody{config: mbq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, mbq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (mbq *MsgBodyQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := mbq.querySpec()
	_spec.Node.Columns = mbq.ctx.Fields
	if len(mbq.ctx.Fields) > 0 {
		_spec.Unique = mbq.ctx.Unique != nil && *mbq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, mbq.driver, _spec)
}

func (mbq *MsgBodyQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(msgbody.Table, msgbody.Columns, sqlgraph.NewFieldSpec(msgbody.FieldID, field.TypeInt))
	_spec.From = mbq.sql
	if unique := mbq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if mbq.path != nil {
		_spec.Unique = true
	}
	if fields := mbq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, msgbody.FieldID)
		for i := range fields {
			if fields[i] != msgbody.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := mbq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := mbq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := mbq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := mbq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (mbq *MsgBodyQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(mbq.driver.Dialect())
	t1 := builder.Table(msgbody.Table)
	columns := mbq.ctx.Fields
	if len(columns) == 0 {
		columns = msgbody.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if mbq.sql != nil {
		selector = mbq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if mbq.ctx.Unique != nil && *mbq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range mbq.predicates {
		p(selector)
	}
	for _, p := range mbq.order {
		p(selector)
	}
	if offset := mbq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := mbq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// MsgBodyGroupBy is the group-by builder for MsgBody entities.
type MsgBodyGroupBy struct {
	selector
	build *MsgBodyQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (mbgb *MsgBodyGroupBy) Aggregate(fns ...AggregateFunc) *MsgBodyGroupBy {
	mbgb.fns = append(mbgb.fns, fns...)
	return mbgb
}

// Scan applies the selector query and scans the result into the given value.
func (mbgb *MsgBodyGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mbgb.build.ctx, "GroupBy")
	if err := mbgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MsgBodyQuery, *MsgBodyGroupBy](ctx, mbgb.build, mbgb, mbgb.build.inters, v)
}

func (mbgb *MsgBodyGroupBy) sqlScan(ctx context.Context, root *MsgBodyQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(mbgb.fns))
	for _, fn := range mbgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*mbgb.flds)+len(mbgb.fns))
		for _, f := range *mbgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*mbgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mbgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// MsgBodySelect is the builder for selecting fields of MsgBody entities.
type MsgBodySelect struct {
	*MsgBodyQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (mbs *MsgBodySelect) Aggregate(fns ...AggregateFunc) *MsgBodySelect {
	mbs.fns = append(mbs.fns, fns...)
	return mbs
}

// Scan applies the selector query and scans the result into the given value.
func (mbs *MsgBodySelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, mbs.ctx, "Select")
	if err := mbs.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*MsgBodyQuery, *MsgBodySelect](ctx, mbs.MsgBodyQuery, mbs, mbs.inters, v)
}

func (mbs *MsgBodySelect) sqlScan(ctx context.Context, root *MsgBodyQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(mbs.fns))
	for _, fn := range mbs.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*mbs.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := mbs.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
