// Code generated by ent, DO NOT EDIT.

package msgbody

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the msgbody type in the database.
	Label = "msg_body"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "msg_id"
	// FieldBody holds the string denoting the body field in the database.
	FieldBody = "body"
	// FieldCts holds the string denoting the cts field in the database.
	FieldCts = "cts"
	// Table holds the table name of the msgbody in the database.
	Table = "msg_body"
)

// Columns holds all SQL columns for msgbody fields.
var Columns = []string{
	FieldID,
	FieldBody,
	FieldCts,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the MsgBody queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByBody orders the results by the body field.
func ByBody(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBody, opts...).ToFunc()
}

// ByCts orders the results by the cts field.
func ByCts(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCts, opts...).ToFunc()
}
