// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Friend is the predicate function for friend builders.
type Friend func(*sql.Selector)

// MsgBody is the predicate function for msgbody builders.
type MsgBody func(*sql.Selector)

// UserInfo is the predicate function for userinfo builders.
type UserInfo func(*sql.Selector)
