// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: chat_api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HandleReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key  string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Data string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *HandleReq) Reset() {
	*x = HandleReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HandleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HandleReq) ProtoMessage() {}

func (x *HandleReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HandleReq.ProtoReflect.Descriptor instead.
func (*HandleReq) Descriptor() ([]byte, []int) {
	return file_chat_api_proto_rawDescGZIP(), []int{0}
}

func (x *HandleReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *HandleReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type PChatMsgSendReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri        int32  `protobuf:"varint,1,opt,name=uri,proto3" json:"uri,omitempty"`
	AppId      int32  `protobuf:"varint,2,opt,name=appId,proto3" json:"appId,omitempty"`
	Channel    int32  `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	MsgUuid    string `protobuf:"bytes,4,opt,name=msgUuid,proto3" json:"msgUuid,omitempty"`
	FromUid    int64  `protobuf:"varint,5,opt,name=fromUid,proto3" json:"fromUid,omitempty"`
	FromName   string `protobuf:"bytes,6,opt,name=fromName,proto3" json:"fromName,omitempty"`
	ToUid      int64  `protobuf:"varint,7,opt,name=toUid,proto3" json:"toUid,omitempty"`
	ToAppId    int32  `protobuf:"varint,8,opt,name=toAppId,proto3" json:"toAppId,omitempty"`
	MsgType    int32  `protobuf:"varint,9,opt,name=msgType,proto3" json:"msgType,omitempty"`
	Message    string `protobuf:"bytes,10,opt,name=message,proto3" json:"message,omitempty"`
	Cts        int64  `protobuf:"varint,11,opt,name=cts,proto3" json:"cts,omitempty"`
	DeviceType int32  `protobuf:"varint,12,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	DeviceId   string `protobuf:"bytes,13,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Extension  string `protobuf:"bytes,14,opt,name=extension,proto3" json:"extension,omitempty"`
	// 服务端生成
	MsgId int64 `protobuf:"varint,15,opt,name=msgId,proto3" json:"msgId,omitempty"`
	SeqId int64 `protobuf:"varint,16,opt,name=seqId,proto3" json:"seqId,omitempty"`
	Sts   int64 `protobuf:"varint,17,opt,name=sts,proto3" json:"sts,omitempty"`
}

func (x *PChatMsgSendReq) Reset() {
	*x = PChatMsgSendReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chat_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PChatMsgSendReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PChatMsgSendReq) ProtoMessage() {}

func (x *PChatMsgSendReq) ProtoReflect() protoreflect.Message {
	mi := &file_chat_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PChatMsgSendReq.ProtoReflect.Descriptor instead.
func (*PChatMsgSendReq) Descriptor() ([]byte, []int) {
	return file_chat_api_proto_rawDescGZIP(), []int{1}
}

func (x *PChatMsgSendReq) GetUri() int32 {
	if x != nil {
		return x.Uri
	}
	return 0
}

func (x *PChatMsgSendReq) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *PChatMsgSendReq) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *PChatMsgSendReq) GetMsgUuid() string {
	if x != nil {
		return x.MsgUuid
	}
	return ""
}

func (x *PChatMsgSendReq) GetFromUid() int64 {
	if x != nil {
		return x.FromUid
	}
	return 0
}

func (x *PChatMsgSendReq) GetFromName() string {
	if x != nil {
		return x.FromName
	}
	return ""
}

func (x *PChatMsgSendReq) GetToUid() int64 {
	if x != nil {
		return x.ToUid
	}
	return 0
}

func (x *PChatMsgSendReq) GetToAppId() int32 {
	if x != nil {
		return x.ToAppId
	}
	return 0
}

func (x *PChatMsgSendReq) GetMsgType() int32 {
	if x != nil {
		return x.MsgType
	}
	return 0
}

func (x *PChatMsgSendReq) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PChatMsgSendReq) GetCts() int64 {
	if x != nil {
		return x.Cts
	}
	return 0
}

func (x *PChatMsgSendReq) GetDeviceType() int32 {
	if x != nil {
		return x.DeviceType
	}
	return 0
}

func (x *PChatMsgSendReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PChatMsgSendReq) GetExtension() string {
	if x != nil {
		return x.Extension
	}
	return ""
}

func (x *PChatMsgSendReq) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *PChatMsgSendReq) GetSeqId() int64 {
	if x != nil {
		return x.SeqId
	}
	return 0
}

func (x *PChatMsgSendReq) GetSts() int64 {
	if x != nil {
		return x.Sts
	}
	return 0
}

var File_chat_api_proto protoreflect.FileDescriptor

var file_chat_api_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x03, 0x61, 0x70, 0x69, 0x1a, 0x0c, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x09, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x52, 0x65, 0x71,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xb1, 0x03, 0x0a, 0x0f, 0x50, 0x43, 0x68, 0x61, 0x74,
	0x4d, 0x73, 0x67, 0x53, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x14, 0x0a, 0x05,
	0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x73, 0x67, 0x55, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d,
	0x73, 0x67, 0x55, 0x75, 0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x69, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x66, 0x72, 0x6f, 0x6d, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x55, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x74, 0x6f, 0x55,
	0x69, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x74, 0x6f, 0x41, 0x70, 0x70, 0x49, 0x64, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x6f, 0x41, 0x70, 0x70, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x6d, 0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6d,
	0x73, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x63, 0x74, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63,
	0x74, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x18, 0x0c, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x0d,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x09, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x65, 0x78, 0x74, 0x65, 0x6e, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05,
	0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x73, 0x67,
	0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x65, 0x71, 0x49, 0x64, 0x18, 0x10, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x05, 0x73, 0x65, 0x71, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x74, 0x73, 0x18,
	0x11, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x74, 0x73, 0x32, 0x36, 0x0a, 0x0b, 0x43, 0x68,
	0x61, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x27, 0x0a, 0x06, 0x48, 0x61, 0x6e,
	0x64, 0x6c, 0x65, 0x12, 0x0e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chat_api_proto_rawDescOnce sync.Once
	file_chat_api_proto_rawDescData = file_chat_api_proto_rawDesc
)

func file_chat_api_proto_rawDescGZIP() []byte {
	file_chat_api_proto_rawDescOnce.Do(func() {
		file_chat_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_chat_api_proto_rawDescData)
	})
	return file_chat_api_proto_rawDescData
}

var file_chat_api_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_chat_api_proto_goTypes = []interface{}{
	(*HandleReq)(nil),       // 0: api.HandleReq
	(*PChatMsgSendReq)(nil), // 1: api.PChatMsgSendReq
	(*Result)(nil),          // 2: api.Result
}
var file_chat_api_proto_depIdxs = []int32{
	0, // 0: api.ChatService.Handle:input_type -> api.HandleReq
	2, // 1: api.ChatService.Handle:output_type -> api.Result
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_chat_api_proto_init() }
func file_chat_api_proto_init() {
	if File_chat_api_proto != nil {
		return
	}
	file_result_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_chat_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HandleReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chat_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PChatMsgSendReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chat_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chat_api_proto_goTypes,
		DependencyIndexes: file_chat_api_proto_depIdxs,
		MessageInfos:      file_chat_api_proto_msgTypes,
	}.Build()
	File_chat_api_proto = out.File
	file_chat_api_proto_rawDesc = nil
	file_chat_api_proto_goTypes = nil
	file_chat_api_proto_depIdxs = nil
}
