// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.8
// - protoc             v4.25.3
// source: chat_api.proto

package api

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// ChatServiceClient is the client API for ChatService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatServiceClient interface {
	Handle(ctx context.Context, in *HandleReq, opts ...grpc_go.CallOption) (*Result, common.ErrorWithAttachment)
}

type chatServiceClient struct {
	cc *triple.TripleConn
}

type ChatServiceClientImpl struct {
	Handle func(ctx context.Context, in *HandleReq) (*Result, error)
}

func (c *ChatServiceClientImpl) GetDubboStub(cc *triple.TripleConn) ChatServiceClient {
	return NewChatServiceClient(cc)
}

func (c *ChatServiceClientImpl) XXX_InterfaceName() string {
	return "api.ChatService"
}

func NewChatServiceClient(cc *triple.TripleConn) ChatServiceClient {
	return &chatServiceClient{cc}
}

func (c *chatServiceClient) Handle(ctx context.Context, in *HandleReq, opts ...grpc_go.CallOption) (*Result, common.ErrorWithAttachment) {
	out := new(Result)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/Handle", in, out)
}

// ChatServiceServer is the server API for ChatService service.
// All implementations must embed UnimplementedChatServiceServer
// for forward compatibility
type ChatServiceServer interface {
	Handle(context.Context, *HandleReq) (*Result, error)
	mustEmbedUnimplementedChatServiceServer()
}

// UnimplementedChatServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChatServiceServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedChatServiceServer) Handle(context.Context, *HandleReq) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handle not implemented")
}
func (s *UnimplementedChatServiceServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedChatServiceServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedChatServiceServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &ChatService_ServiceDesc
}
func (s *UnimplementedChatServiceServer) XXX_InterfaceName() string {
	return "api.ChatService"
}

func (UnimplementedChatServiceServer) mustEmbedUnimplementedChatServiceServer() {}

// UnsafeChatServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatServiceServer will
// result in compilation errors.
type UnsafeChatServiceServer interface {
	mustEmbedUnimplementedChatServiceServer()
}

func RegisterChatServiceServer(s grpc_go.ServiceRegistrar, srv ChatServiceServer) {
	s.RegisterService(&ChatService_ServiceDesc, srv)
}

func _ChatService_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(HandleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("Handle", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// ChatService_ServiceDesc is the grpc_go.ServiceDesc for ChatService service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatService_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "api.ChatService",
	HandlerType: (*ChatServiceServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "Handle",
			Handler:    _ChatService_Handle_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "chat_api.proto",
}
