// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.8
// - protoc             v4.25.3
// source: friend_api.proto

package api

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// FriendServiceClient is the client API for FriendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FriendServiceClient interface {
	FriendList(ctx context.Context, in *FriendListReq, opts ...grpc_go.CallOption) (*Result, common.ErrorWithAttachment)
}

type friendServiceClient struct {
	cc *triple.TripleConn
}

type FriendServiceClientImpl struct {
	FriendList func(ctx context.Context, in *FriendListReq) (*Result, error)
}

func (c *FriendServiceClientImpl) GetDubboStub(cc *triple.TripleConn) FriendServiceClient {
	return NewFriendServiceClient(cc)
}

func (c *FriendServiceClientImpl) XXX_InterfaceName() string {
	return "api.FriendService"
}

func NewFriendServiceClient(cc *triple.TripleConn) FriendServiceClient {
	return &friendServiceClient{cc}
}

func (c *friendServiceClient) FriendList(ctx context.Context, in *FriendListReq, opts ...grpc_go.CallOption) (*Result, common.ErrorWithAttachment) {
	out := new(Result)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/FriendList", in, out)
}

// FriendServiceServer is the server API for FriendService service.
// All implementations must embed UnimplementedFriendServiceServer
// for forward compatibility
type FriendServiceServer interface {
	FriendList(context.Context, *FriendListReq) (*Result, error)
	mustEmbedUnimplementedFriendServiceServer()
}

// UnimplementedFriendServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFriendServiceServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedFriendServiceServer) FriendList(context.Context, *FriendListReq) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FriendList not implemented")
}
func (s *UnimplementedFriendServiceServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedFriendServiceServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedFriendServiceServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &FriendService_ServiceDesc
}
func (s *UnimplementedFriendServiceServer) XXX_InterfaceName() string {
	return "api.FriendService"
}

func (UnimplementedFriendServiceServer) mustEmbedUnimplementedFriendServiceServer() {}

// UnsafeFriendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FriendServiceServer will
// result in compilation errors.
type UnsafeFriendServiceServer interface {
	mustEmbedUnimplementedFriendServiceServer()
}

func RegisterFriendServiceServer(s grpc_go.ServiceRegistrar, srv FriendServiceServer) {
	s.RegisterService(&FriendService_ServiceDesc, srv)
}

func _FriendService_FriendList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(FriendListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("FriendList", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// FriendService_ServiceDesc is the grpc_go.ServiceDesc for FriendService service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var FriendService_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "api.FriendService",
	HandlerType: (*FriendServiceServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "FriendList",
			Handler:    _FriendService_FriendList_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "friend_api.proto",
}
