// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.8
// - protoc             v4.25.3
// source: im_api.proto

package api

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// SyncServiceClient is the client API for SyncService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SyncServiceClient interface {
	Sync(ctx context.Context, in *SyncReq, opts ...grpc_go.CallOption) (*Result, common.ErrorWithAttachment)
}

type syncServiceClient struct {
	cc *triple.TripleConn
}

type SyncServiceClientImpl struct {
	Sync func(ctx context.Context, in *SyncReq) (*Result, error)
}

func (c *SyncServiceClientImpl) GetDubboStub(cc *triple.TripleConn) SyncServiceClient {
	return NewSyncServiceClient(cc)
}

func (c *SyncServiceClientImpl) XXX_InterfaceName() string {
	return "api.SyncService"
}

func NewSyncServiceClient(cc *triple.TripleConn) SyncServiceClient {
	return &syncServiceClient{cc}
}

func (c *syncServiceClient) Sync(ctx context.Context, in *SyncReq, opts ...grpc_go.CallOption) (*Result, common.ErrorWithAttachment) {
	out := new(Result)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/Sync", in, out)
}

// SyncServiceServer is the server API for SyncService service.
// All implementations must embed UnimplementedSyncServiceServer
// for forward compatibility
type SyncServiceServer interface {
	Sync(context.Context, *SyncReq) (*Result, error)
	mustEmbedUnimplementedSyncServiceServer()
}

// UnimplementedSyncServiceServer must be embedded to have forward compatible implementations.
type UnimplementedSyncServiceServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedSyncServiceServer) Sync(context.Context, *SyncReq) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Sync not implemented")
}
func (s *UnimplementedSyncServiceServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedSyncServiceServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedSyncServiceServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &SyncService_ServiceDesc
}
func (s *UnimplementedSyncServiceServer) XXX_InterfaceName() string {
	return "api.SyncService"
}

func (UnimplementedSyncServiceServer) mustEmbedUnimplementedSyncServiceServer() {}

// UnsafeSyncServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SyncServiceServer will
// result in compilation errors.
type UnsafeSyncServiceServer interface {
	mustEmbedUnimplementedSyncServiceServer()
}

func RegisterSyncServiceServer(s grpc_go.ServiceRegistrar, srv SyncServiceServer) {
	s.RegisterService(&SyncService_ServiceDesc, srv)
}

func _SyncService_Sync_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(SyncReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("Sync", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// SyncService_ServiceDesc is the grpc_go.ServiceDesc for SyncService service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var SyncService_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "api.SyncService",
	HandlerType: (*SyncServiceServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "Sync",
			Handler:    _SyncService_Sync_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "im_api.proto",
}

// BatchServiceClient is the client API for BatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BatchServiceClient interface {
	Batch(ctx context.Context, in *PBatch, opts ...grpc_go.CallOption) (*Result, common.ErrorWithAttachment)
}

type batchServiceClient struct {
	cc *triple.TripleConn
}

type BatchServiceClientImpl struct {
	Batch func(ctx context.Context, in *PBatch) (*Result, error)
}

func (c *BatchServiceClientImpl) GetDubboStub(cc *triple.TripleConn) BatchServiceClient {
	return NewBatchServiceClient(cc)
}

func (c *BatchServiceClientImpl) XXX_InterfaceName() string {
	return "api.BatchService"
}

func NewBatchServiceClient(cc *triple.TripleConn) BatchServiceClient {
	return &batchServiceClient{cc}
}

func (c *batchServiceClient) Batch(ctx context.Context, in *PBatch, opts ...grpc_go.CallOption) (*Result, common.ErrorWithAttachment) {
	out := new(Result)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/Batch", in, out)
}

// BatchServiceServer is the server API for BatchService service.
// All implementations must embed UnimplementedBatchServiceServer
// for forward compatibility
type BatchServiceServer interface {
	Batch(context.Context, *PBatch) (*Result, error)
	mustEmbedUnimplementedBatchServiceServer()
}

// UnimplementedBatchServiceServer must be embedded to have forward compatible implementations.
type UnimplementedBatchServiceServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedBatchServiceServer) Batch(context.Context, *PBatch) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Batch not implemented")
}
func (s *UnimplementedBatchServiceServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedBatchServiceServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedBatchServiceServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &BatchService_ServiceDesc
}
func (s *UnimplementedBatchServiceServer) XXX_InterfaceName() string {
	return "api.BatchService"
}

func (UnimplementedBatchServiceServer) mustEmbedUnimplementedBatchServiceServer() {}

// UnsafeBatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BatchServiceServer will
// result in compilation errors.
type UnsafeBatchServiceServer interface {
	mustEmbedUnimplementedBatchServiceServer()
}

func RegisterBatchServiceServer(s grpc_go.ServiceRegistrar, srv BatchServiceServer) {
	s.RegisterService(&BatchService_ServiceDesc, srv)
}

func _BatchService_Batch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(PBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("Batch", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// BatchService_ServiceDesc is the grpc_go.ServiceDesc for BatchService service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var BatchService_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "api.BatchService",
	HandlerType: (*BatchServiceServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "Batch",
			Handler:    _BatchService_Batch_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "im_api.proto",
}
