// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: im_api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SyncReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uid     int64 `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	AppId   int32 `protobuf:"varint,2,opt,name=appId,proto3" json:"appId,omitempty"`
	Channel int32 `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	// 客户端本地最大同步位点
	LocalSyncPos int64 `protobuf:"varint,4,opt,name=localSyncPos,proto3" json:"localSyncPos,omitempty"`
}

func (x *SyncReq) Reset() {
	*x = SyncReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncReq) ProtoMessage() {}

func (x *SyncReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncReq.ProtoReflect.Descriptor instead.
func (*SyncReq) Descriptor() ([]byte, []int) {
	return file_im_api_proto_rawDescGZIP(), []int{0}
}

func (x *SyncReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *SyncReq) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *SyncReq) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *SyncReq) GetLocalSyncPos() int64 {
	if x != nil {
		return x.LocalSyncPos
	}
	return 0
}

type SyncResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Members  []*SyncMember `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	Messages []string      `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	HasMore  bool          `protobuf:"varint,3,opt,name=hasMore,proto3" json:"hasMore,omitempty"`
}

func (x *SyncResp) Reset() {
	*x = SyncResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncResp) ProtoMessage() {}

func (x *SyncResp) ProtoReflect() protoreflect.Message {
	mi := &file_im_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncResp.ProtoReflect.Descriptor instead.
func (*SyncResp) Descriptor() ([]byte, []int) {
	return file_im_api_proto_rawDescGZIP(), []int{1}
}

func (x *SyncResp) GetMembers() []*SyncMember {
	if x != nil {
		return x.Members
	}
	return nil
}

func (x *SyncResp) GetMessages() []string {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *SyncResp) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type SyncMember struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SyncPos int64 `protobuf:"varint,1,opt,name=syncPos,proto3" json:"syncPos,omitempty"`
	MsgId   int64 `protobuf:"varint,2,opt,name=msgId,proto3" json:"msgId,omitempty"`
}

func (x *SyncMember) Reset() {
	*x = SyncMember{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SyncMember) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncMember) ProtoMessage() {}

func (x *SyncMember) ProtoReflect() protoreflect.Message {
	mi := &file_im_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncMember.ProtoReflect.Descriptor instead.
func (*SyncMember) Descriptor() ([]byte, []int) {
	return file_im_api_proto_rawDescGZIP(), []int{2}
}

func (x *SyncMember) GetSyncPos() int64 {
	if x != nil {
		return x.SyncPos
	}
	return 0
}

func (x *SyncMember) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

type PSyncReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri     int32 `protobuf:"varint,1,opt,name=uri,proto3" json:"uri,omitempty"`
	AppId   int32 `protobuf:"varint,2,opt,name=appId,proto3" json:"appId,omitempty"`
	Channel int32 `protobuf:"varint,3,opt,name=channel,proto3" json:"channel,omitempty"`
	Uid     int64 `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	// *
	// 不为空只同步给该设备，否则同步给所有设备
	// 一般情况下，deviceId不为空的包都不需要同步
	DeviceId string `protobuf:"bytes,5,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	// *
	// @see ChatType
	ChatType int32 `protobuf:"varint,6,opt,name=chatType,proto3" json:"chatType,omitempty"`
	// *
	// data字段代表的协议的msgId，syncPos=NEED_SYNC时此字段必须
	MsgId int64 `protobuf:"varint,7,opt,name=msgId,proto3" json:"msgId,omitempty"`
	// *
	// 需要同步的数据
	Data string `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
	// *
	// 服务端同步位点 小于0 : 不需要同步 等于0 : 需要同步，具体值由sync服务填充
	SyncPos int64 `protobuf:"varint,9,opt,name=syncPos,proto3" json:"syncPos,omitempty"`
	// *
	// 离线push配置
	//
	// @see PushType
	PushType int32 `protobuf:"varint,10,opt,name=pushType,proto3" json:"pushType,omitempty"`
}

func (x *PSyncReq) Reset() {
	*x = PSyncReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PSyncReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PSyncReq) ProtoMessage() {}

func (x *PSyncReq) ProtoReflect() protoreflect.Message {
	mi := &file_im_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PSyncReq.ProtoReflect.Descriptor instead.
func (*PSyncReq) Descriptor() ([]byte, []int) {
	return file_im_api_proto_rawDescGZIP(), []int{3}
}

func (x *PSyncReq) GetUri() int32 {
	if x != nil {
		return x.Uri
	}
	return 0
}

func (x *PSyncReq) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *PSyncReq) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *PSyncReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PSyncReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PSyncReq) GetChatType() int32 {
	if x != nil {
		return x.ChatType
	}
	return 0
}

func (x *PSyncReq) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *PSyncReq) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

func (x *PSyncReq) GetSyncPos() int64 {
	if x != nil {
		return x.SyncPos
	}
	return 0
}

func (x *PSyncReq) GetPushType() int32 {
	if x != nil {
		return x.PushType
	}
	return 0
}

type PTransDown struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri      int32  `protobuf:"varint,1,opt,name=uri,proto3" json:"uri,omitempty"`
	AppId    int32  `protobuf:"varint,2,opt,name=appId,proto3" json:"appId,omitempty"`
	Uid      int64  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	DeviceId string `protobuf:"bytes,4,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	Channel  int32  `protobuf:"varint,5,opt,name=channel,proto3" json:"channel,omitempty"`
	// *
	// 此消息的同步位点,
	// -1表示此消息不需要同步
	SyncPos int64  `protobuf:"varint,6,opt,name=syncPos,proto3" json:"syncPos,omitempty"`
	MsgId   int64  `protobuf:"varint,7,opt,name=msgId,proto3" json:"msgId,omitempty"`
	Data    string `protobuf:"bytes,8,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PTransDown) Reset() {
	*x = PTransDown{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PTransDown) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTransDown) ProtoMessage() {}

func (x *PTransDown) ProtoReflect() protoreflect.Message {
	mi := &file_im_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTransDown.ProtoReflect.Descriptor instead.
func (*PTransDown) Descriptor() ([]byte, []int) {
	return file_im_api_proto_rawDescGZIP(), []int{4}
}

func (x *PTransDown) GetUri() int32 {
	if x != nil {
		return x.Uri
	}
	return 0
}

func (x *PTransDown) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *PTransDown) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PTransDown) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PTransDown) GetChannel() int32 {
	if x != nil {
		return x.Channel
	}
	return 0
}

func (x *PTransDown) GetSyncPos() int64 {
	if x != nil {
		return x.SyncPos
	}
	return 0
}

func (x *PTransDown) GetMsgId() int64 {
	if x != nil {
		return x.MsgId
	}
	return 0
}

func (x *PTransDown) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type PTransUp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri        int32  `protobuf:"varint,1,opt,name=uri,proto3" json:"uri,omitempty"`
	AppId      int32  `protobuf:"varint,2,opt,name=appId,proto3" json:"appId,omitempty"`
	Uid        int64  `protobuf:"varint,3,opt,name=uid,proto3" json:"uid,omitempty"`
	DeviceType int32  `protobuf:"varint,4,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	DeviceId   string `protobuf:"bytes,5,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	// *
	// 上行链路会使用此字段进行服务路由,
	// 将相同routeKey的请求打到同一台机器的同一个线程处理,
	// 尽量保证消息的顺序性
	RouteKey string `protobuf:"bytes,6,opt,name=routeKey,proto3" json:"routeKey,omitempty"`
	Data     string `protobuf:"bytes,7,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PTransUp) Reset() {
	*x = PTransUp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PTransUp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PTransUp) ProtoMessage() {}

func (x *PTransUp) ProtoReflect() protoreflect.Message {
	mi := &file_im_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PTransUp.ProtoReflect.Descriptor instead.
func (*PTransUp) Descriptor() ([]byte, []int) {
	return file_im_api_proto_rawDescGZIP(), []int{5}
}

func (x *PTransUp) GetUri() int32 {
	if x != nil {
		return x.Uri
	}
	return 0
}

func (x *PTransUp) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *PTransUp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PTransUp) GetDeviceType() int32 {
	if x != nil {
		return x.DeviceType
	}
	return 0
}

func (x *PTransUp) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PTransUp) GetRouteKey() string {
	if x != nil {
		return x.RouteKey
	}
	return ""
}

func (x *PTransUp) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

type PBatch struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri  int32    `protobuf:"varint,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Data []string `protobuf:"bytes,2,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *PBatch) Reset() {
	*x = PBatch{}
	if protoimpl.UnsafeEnabled {
		mi := &file_im_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PBatch) ProtoMessage() {}

func (x *PBatch) ProtoReflect() protoreflect.Message {
	mi := &file_im_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PBatch.ProtoReflect.Descriptor instead.
func (*PBatch) Descriptor() ([]byte, []int) {
	return file_im_api_proto_rawDescGZIP(), []int{6}
}

func (x *PBatch) GetUri() int32 {
	if x != nil {
		return x.Uri
	}
	return 0
}

func (x *PBatch) GetData() []string {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_im_api_proto protoreflect.FileDescriptor

var file_im_api_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x69, 0x6d, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03,
	0x61, 0x70, 0x69, 0x1a, 0x0c, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x6f, 0x0a, 0x07, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14,
	0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61,
	0x70, 0x70, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x22,
	0x0a, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x79, 0x6e, 0x63, 0x50, 0x6f, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x6c, 0x6f, 0x63, 0x61, 0x6c, 0x53, 0x79, 0x6e, 0x63, 0x50,
	0x6f, 0x73, 0x22, 0x6b, 0x0a, 0x08, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x73, 0x70, 0x12, 0x29,
	0x0a, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x0f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72,
	0x52, 0x07, 0x6d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x6d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x4d, 0x6f, 0x72, 0x65, 0x22,
	0x3c, 0x0a, 0x0a, 0x53, 0x79, 0x6e, 0x63, 0x4d, 0x65, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x79, 0x6e, 0x63, 0x50, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x73, 0x79, 0x6e, 0x63, 0x50, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x22, 0xf6, 0x01,
	0x0a, 0x08, 0x50, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72,
	0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x14, 0x0a, 0x05,
	0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70,
	0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x10, 0x0a, 0x03,
	0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x1a,
	0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x68,
	0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x68,
	0x61, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x18, 0x0a, 0x07, 0x73, 0x79, 0x6e, 0x63, 0x50, 0x6f, 0x73, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x73, 0x79, 0x6e, 0x63, 0x50, 0x6f, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x75,
	0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x75,
	0x73, 0x68, 0x54, 0x79, 0x70, 0x65, 0x22, 0xc0, 0x01, 0x0a, 0x0a, 0x50, 0x54, 0x72, 0x61, 0x6e,
	0x73, 0x44, 0x6f, 0x77, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12,
	0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x63,
	0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x68,
	0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x79, 0x6e, 0x63, 0x50, 0x6f, 0x73,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x73, 0x79, 0x6e, 0x63, 0x50, 0x6f, 0x73, 0x12,
	0x14, 0x0a, 0x05, 0x6d, 0x73, 0x67, 0x49, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x6d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0xb0, 0x01, 0x0a, 0x08, 0x50, 0x54,
	0x72, 0x61, 0x6e, 0x73, 0x55, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x1e, 0x0a, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08,
	0x72, 0x6f, 0x75, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2e, 0x0a, 0x06,
	0x50, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x32, 0x32, 0x0a, 0x0b,
	0x53, 0x79, 0x6e, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x53,
	0x79, 0x6e, 0x63, 0x12, 0x0c, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x79, 0x6e, 0x63, 0x52, 0x65,
	0x71, 0x1a, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x22, 0x00,
	0x32, 0x33, 0x0a, 0x0c, 0x42, 0x61, 0x74, 0x63, 0x68, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x23, 0x0a, 0x05, 0x42, 0x61, 0x74, 0x63, 0x68, 0x12, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x50, 0x42, 0x61, 0x74, 0x63, 0x68, 0x1a, 0x0b, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73,
	0x75, 0x6c, 0x74, 0x22, 0x00, 0x42, 0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x61, 0x70, 0x69, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_im_api_proto_rawDescOnce sync.Once
	file_im_api_proto_rawDescData = file_im_api_proto_rawDesc
)

func file_im_api_proto_rawDescGZIP() []byte {
	file_im_api_proto_rawDescOnce.Do(func() {
		file_im_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_im_api_proto_rawDescData)
	})
	return file_im_api_proto_rawDescData
}

var file_im_api_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_im_api_proto_goTypes = []interface{}{
	(*SyncReq)(nil),    // 0: api.SyncReq
	(*SyncResp)(nil),   // 1: api.SyncResp
	(*SyncMember)(nil), // 2: api.SyncMember
	(*PSyncReq)(nil),   // 3: api.PSyncReq
	(*PTransDown)(nil), // 4: api.PTransDown
	(*PTransUp)(nil),   // 5: api.PTransUp
	(*PBatch)(nil),     // 6: api.PBatch
	(*Result)(nil),     // 7: api.Result
}
var file_im_api_proto_depIdxs = []int32{
	2, // 0: api.SyncResp.members:type_name -> api.SyncMember
	0, // 1: api.SyncService.Sync:input_type -> api.SyncReq
	6, // 2: api.BatchService.Batch:input_type -> api.PBatch
	7, // 3: api.SyncService.Sync:output_type -> api.Result
	7, // 4: api.BatchService.Batch:output_type -> api.Result
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_im_api_proto_init() }
func file_im_api_proto_init() {
	if File_im_api_proto != nil {
		return
	}
	file_result_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_im_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SyncMember); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PSyncReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PTransDown); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PTransUp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_im_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PBatch); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_im_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_im_api_proto_goTypes,
		DependencyIndexes: file_im_api_proto_depIdxs,
		MessageInfos:      file_im_api_proto_msgTypes,
	}.Build()
	File_im_api_proto = out.File
	file_im_api_proto_rawDesc = nil
	file_im_api_proto_goTypes = nil
	file_im_api_proto_depIdxs = nil
}
