// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.3
// source: login_api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PLoginReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri        int32  `protobuf:"varint,1,opt,name=uri,proto3" json:"uri,omitempty"`
	AppId      int32  `protobuf:"varint,2,opt,name=appId,proto3" json:"appId,omitempty"`
	RequestId  string `protobuf:"bytes,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Uid        int64  `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Token      string `protobuf:"bytes,5,opt,name=token,proto3" json:"token,omitempty"`
	DeviceId   string `protobuf:"bytes,6,opt,name=deviceId,proto3" json:"deviceId,omitempty"`
	DeviceType int32  `protobuf:"varint,7,opt,name=deviceType,proto3" json:"deviceType,omitempty"`
	Os         string `protobuf:"bytes,8,opt,name=os,proto3" json:"os,omitempty"`
	SdkVersion string `protobuf:"bytes,9,opt,name=sdkVersion,proto3" json:"sdkVersion,omitempty"`
	PushToken  string `protobuf:"bytes,10,opt,name=pushToken,proto3" json:"pushToken,omitempty"`
	Cts        int64  `protobuf:"varint,11,opt,name=cts,proto3" json:"cts,omitempty"`
}

func (x *PLoginReq) Reset() {
	*x = PLoginReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PLoginReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PLoginReq) ProtoMessage() {}

func (x *PLoginReq) ProtoReflect() protoreflect.Message {
	mi := &file_login_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PLoginReq.ProtoReflect.Descriptor instead.
func (*PLoginReq) Descriptor() ([]byte, []int) {
	return file_login_api_proto_rawDescGZIP(), []int{0}
}

func (x *PLoginReq) GetUri() int32 {
	if x != nil {
		return x.Uri
	}
	return 0
}

func (x *PLoginReq) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *PLoginReq) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PLoginReq) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PLoginReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *PLoginReq) GetDeviceId() string {
	if x != nil {
		return x.DeviceId
	}
	return ""
}

func (x *PLoginReq) GetDeviceType() int32 {
	if x != nil {
		return x.DeviceType
	}
	return 0
}

func (x *PLoginReq) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *PLoginReq) GetSdkVersion() string {
	if x != nil {
		return x.SdkVersion
	}
	return ""
}

func (x *PLoginReq) GetPushToken() string {
	if x != nil {
		return x.PushToken
	}
	return ""
}

func (x *PLoginReq) GetCts() int64 {
	if x != nil {
		return x.Cts
	}
	return 0
}

type PLoginResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri       int32  `protobuf:"varint,1,opt,name=uri,proto3" json:"uri,omitempty"`
	AppId     int32  `protobuf:"varint,2,opt,name=appId,proto3" json:"appId,omitempty"`
	RequestId string `protobuf:"bytes,3,opt,name=requestId,proto3" json:"requestId,omitempty"`
	Uid       int64  `protobuf:"varint,4,opt,name=uid,proto3" json:"uid,omitempty"`
	Code      int32  `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	Cause     string `protobuf:"bytes,6,opt,name=cause,proto3" json:"cause,omitempty"`
}

func (x *PLoginResp) Reset() {
	*x = PLoginResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PLoginResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PLoginResp) ProtoMessage() {}

func (x *PLoginResp) ProtoReflect() protoreflect.Message {
	mi := &file_login_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PLoginResp.ProtoReflect.Descriptor instead.
func (*PLoginResp) Descriptor() ([]byte, []int) {
	return file_login_api_proto_rawDescGZIP(), []int{1}
}

func (x *PLoginResp) GetUri() int32 {
	if x != nil {
		return x.Uri
	}
	return 0
}

func (x *PLoginResp) GetAppId() int32 {
	if x != nil {
		return x.AppId
	}
	return 0
}

func (x *PLoginResp) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *PLoginResp) GetUid() int64 {
	if x != nil {
		return x.Uid
	}
	return 0
}

func (x *PLoginResp) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PLoginResp) GetCause() string {
	if x != nil {
		return x.Cause
	}
	return ""
}

type PKickOff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Uri      int32  `protobuf:"varint,1,opt,name=uri,proto3" json:"uri,omitempty"`
	Code     int32  `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Msg      string `protobuf:"bytes,3,opt,name=msg,proto3" json:"msg,omitempty"`
	SocketId string `protobuf:"bytes,4,opt,name=socketId,proto3" json:"socketId,omitempty"`
}

func (x *PKickOff) Reset() {
	*x = PKickOff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_login_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PKickOff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PKickOff) ProtoMessage() {}

func (x *PKickOff) ProtoReflect() protoreflect.Message {
	mi := &file_login_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PKickOff.ProtoReflect.Descriptor instead.
func (*PKickOff) Descriptor() ([]byte, []int) {
	return file_login_api_proto_rawDescGZIP(), []int{2}
}

func (x *PKickOff) GetUri() int32 {
	if x != nil {
		return x.Uri
	}
	return 0
}

func (x *PKickOff) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PKickOff) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *PKickOff) GetSocketId() string {
	if x != nil {
		return x.SocketId
	}
	return ""
}

var File_login_api_proto protoreflect.FileDescriptor

var file_login_api_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x6c, 0x6f, 0x67, 0x69, 0x6e, 0x5f, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x95, 0x02, 0x0a, 0x09, 0x50, 0x4c, 0x6f, 0x67, 0x69,
	0x6e, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09,
	0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69,
	0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x49, 0x64, 0x12, 0x1e,
	0x0a, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x0e,
	0x0a, 0x02, 0x6f, 0x73, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x1e,
	0x0a, 0x0a, 0x73, 0x64, 0x6b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x73, 0x64, 0x6b, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1c,
	0x0a, 0x09, 0x70, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x0a, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x70, 0x75, 0x73, 0x68, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x63, 0x74, 0x73, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x63, 0x74, 0x73, 0x22, 0x8e,
	0x01, 0x0a, 0x0a, 0x50, 0x4c, 0x6f, 0x67, 0x69, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x10, 0x0a,
	0x03, 0x75, 0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12,
	0x14, 0x0a, 0x05, 0x61, 0x70, 0x70, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x61, 0x70, 0x70, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x49, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x63, 0x61, 0x75,
	0x73, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x63, 0x61, 0x75, 0x73, 0x65, 0x22,
	0x5e, 0x0a, 0x08, 0x50, 0x4b, 0x69, 0x63, 0x6b, 0x4f, 0x66, 0x66, 0x12, 0x10, 0x0a, 0x03, 0x75,
	0x72, 0x69, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x75, 0x72, 0x69, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x6f, 0x63, 0x6b, 0x65, 0x74, 0x49, 0x64, 0x42,
	0x08, 0x5a, 0x06, 0x2e, 0x2f, 0x3b, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_login_api_proto_rawDescOnce sync.Once
	file_login_api_proto_rawDescData = file_login_api_proto_rawDesc
)

func file_login_api_proto_rawDescGZIP() []byte {
	file_login_api_proto_rawDescOnce.Do(func() {
		file_login_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_login_api_proto_rawDescData)
	})
	return file_login_api_proto_rawDescData
}

var file_login_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_login_api_proto_goTypes = []interface{}{
	(*PLoginReq)(nil),  // 0: api.PLoginReq
	(*PLoginResp)(nil), // 1: api.PLoginResp
	(*PKickOff)(nil),   // 2: api.PKickOff
}
var file_login_api_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_login_api_proto_init() }
func file_login_api_proto_init() {
	if File_login_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_login_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PLoginReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PLoginResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_login_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PKickOff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_login_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_login_api_proto_goTypes,
		DependencyIndexes: file_login_api_proto_depIdxs,
		MessageInfos:      file_login_api_proto_msgTypes,
	}.Build()
	File_login_api_proto = out.File
	file_login_api_proto_rawDesc = nil
	file_login_api_proto_goTypes = nil
	file_login_api_proto_depIdxs = nil
}
