// Code generated by protoc-gen-go-triple. DO NOT EDIT.
// versions:
// - protoc-gen-go-triple v1.0.8
// - protoc             v4.25.3
// source: message_api.proto

package api

import (
	context "context"
	protocol "dubbo.apache.org/dubbo-go/v3/protocol"
	dubbo3 "dubbo.apache.org/dubbo-go/v3/protocol/dubbo3"
	invocation "dubbo.apache.org/dubbo-go/v3/protocol/invocation"
	grpc_go "github.com/dubbogo/grpc-go"
	codes "github.com/dubbogo/grpc-go/codes"
	metadata "github.com/dubbogo/grpc-go/metadata"
	status "github.com/dubbogo/grpc-go/status"
	common "github.com/dubbogo/triple/pkg/common"
	constant "github.com/dubbogo/triple/pkg/common/constant"
	triple "github.com/dubbogo/triple/pkg/triple"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc_go.SupportPackageIsVersion7

// MessageServiceClient is the client API for MessageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MessageServiceClient interface {
	GetMsgBody(ctx context.Context, in *MsgBodyGetReq, opts ...grpc_go.CallOption) (*Result, common.ErrorWithAttachment)
}

type messageServiceClient struct {
	cc *triple.TripleConn
}

type MessageServiceClientImpl struct {
	GetMsgBody func(ctx context.Context, in *MsgBodyGetReq) (*Result, error)
}

func (c *MessageServiceClientImpl) GetDubboStub(cc *triple.TripleConn) MessageServiceClient {
	return NewMessageServiceClient(cc)
}

func (c *MessageServiceClientImpl) XXX_InterfaceName() string {
	return "api.MessageService"
}

func NewMessageServiceClient(cc *triple.TripleConn) MessageServiceClient {
	return &messageServiceClient{cc}
}

func (c *messageServiceClient) GetMsgBody(ctx context.Context, in *MsgBodyGetReq, opts ...grpc_go.CallOption) (*Result, common.ErrorWithAttachment) {
	out := new(Result)
	interfaceKey := ctx.Value(constant.InterfaceKey).(string)
	return out, c.cc.Invoke(ctx, "/"+interfaceKey+"/GetMsgBody", in, out)
}

// MessageServiceServer is the server API for MessageService service.
// All implementations must embed UnimplementedMessageServiceServer
// for forward compatibility
type MessageServiceServer interface {
	GetMsgBody(context.Context, *MsgBodyGetReq) (*Result, error)
	mustEmbedUnimplementedMessageServiceServer()
}

// UnimplementedMessageServiceServer must be embedded to have forward compatible implementations.
type UnimplementedMessageServiceServer struct {
	proxyImpl protocol.Invoker
}

func (UnimplementedMessageServiceServer) GetMsgBody(context.Context, *MsgBodyGetReq) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMsgBody not implemented")
}
func (s *UnimplementedMessageServiceServer) XXX_SetProxyImpl(impl protocol.Invoker) {
	s.proxyImpl = impl
}

func (s *UnimplementedMessageServiceServer) XXX_GetProxyImpl() protocol.Invoker {
	return s.proxyImpl
}

func (s *UnimplementedMessageServiceServer) XXX_ServiceDesc() *grpc_go.ServiceDesc {
	return &MessageService_ServiceDesc
}
func (s *UnimplementedMessageServiceServer) XXX_InterfaceName() string {
	return "api.MessageService"
}

func (UnimplementedMessageServiceServer) mustEmbedUnimplementedMessageServiceServer() {}

// UnsafeMessageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MessageServiceServer will
// result in compilation errors.
type UnsafeMessageServiceServer interface {
	mustEmbedUnimplementedMessageServiceServer()
}

func RegisterMessageServiceServer(s grpc_go.ServiceRegistrar, srv MessageServiceServer) {
	s.RegisterService(&MessageService_ServiceDesc, srv)
}

func _MessageService_GetMsgBody_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc_go.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgBodyGetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	base := srv.(dubbo3.Dubbo3GrpcService)
	args := []interface{}{}
	args = append(args, in)
	md, _ := metadata.FromIncomingContext(ctx)
	invAttachment := make(map[string]interface{}, len(md))
	for k, v := range md {
		invAttachment[k] = v
	}
	invo := invocation.NewRPCInvocation("GetMsgBody", args, invAttachment)
	if interceptor == nil {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	info := &grpc_go.UnaryServerInfo{
		Server:     srv,
		FullMethod: ctx.Value("XXX_TRIPLE_GO_INTERFACE_NAME").(string),
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		result := base.XXX_GetProxyImpl().Invoke(ctx, invo)
		return result, result.Error()
	}
	return interceptor(ctx, in, info, handler)
}

// MessageService_ServiceDesc is the grpc_go.ServiceDesc for MessageService service.
// It's only intended for direct use with grpc_go.RegisterService,
// and not to be introspected or modified (even as a copy)
var MessageService_ServiceDesc = grpc_go.ServiceDesc{
	ServiceName: "api.MessageService",
	HandlerType: (*MessageServiceServer)(nil),
	Methods: []grpc_go.MethodDesc{
		{
			MethodName: "GetMsgBody",
			Handler:    _MessageService_GetMsgBody_Handler,
		},
	},
	Streams:  []grpc_go.StreamDesc{},
	Metadata: "message_api.proto",
}
