// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/entsql"
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// FriendColumns holds the columns for the "friend" table.
	FriendColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "uid", Type: field.TypeInt64},
		{Name: "peer_uid", Type: field.TypeInt64},
		{Name: "state", Type: field.TypeInt},
		{Name: "cts", Type: field.TypeInt64},
		{Name: "uts", Type: field.TypeInt64},
	}
	// FriendTable holds the schema information for the "friend" table.
	FriendTable = &schema.Table{
		Name:       "friend",
		Columns:    FriendColumns,
		PrimaryKey: []*schema.Column{FriendColumns[0]},
	}
	// MsgBodyColumns holds the columns for the "msg_body" table.
	MsgBodyColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "msg_id", Type: field.TypeInt64},
		{Name: "body", Type: field.TypeString},
		{Name: "cts", Type: field.TypeInt64},
	}
	// MsgBodyTable holds the schema information for the "msg_body" table.
	MsgBodyTable = &schema.Table{
		Name:       "msg_body",
		Columns:    MsgBodyColumns,
		PrimaryKey: []*schema.Column{MsgBodyColumns[0]},
	}
	// UserInfoColumns holds the columns for the "user_info" table.
	UserInfoColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt64, Increment: true},
		{Name: "username", Type: field.TypeString, Size: 100},
		{Name: "password", Type: field.TypeString, Size: 100},
		{Name: "nickname", Type: field.TypeString, Size: 100},
		{Name: "avatar", Type: field.TypeString, Nullable: true, Size: 300},
		{Name: "status", Type: field.TypeInt},
		{Name: "ext", Type: field.TypeString, Nullable: true, Size: 500},
	}
	// UserInfoTable holds the schema information for the "user_info" table.
	UserInfoTable = &schema.Table{
		Name:       "user_info",
		Columns:    UserInfoColumns,
		PrimaryKey: []*schema.Column{UserInfoColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		FriendTable,
		MsgBodyTable,
		UserInfoTable,
	}
)

func init() {
	FriendTable.Annotation = &entsql.Annotation{
		Table: "friend",
	}
	MsgBodyTable.Annotation = &entsql.Annotation{
		Table: "msg_body",
	}
	UserInfoTable.Annotation = &entsql.Annotation{
		Table: "user_info",
	}
}
